services:
  - type: webconvertacolor
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /
      - type: rewrite
        source: /tim
        destination: /cool
